blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ General Discussions
    url: https://github.com/5ouma/opml-generator/discussions/new?category=general
    about: Chat about anything and everything here

  - name: ğŸ™ Q&A
    url: https://github.com/5ouma/opml-generator/discussions/new?category=q-a
    about: Ask the community for help
