name: âœ… CI Checker

on:
  pull_request:

permissions: {}

jobs:
  merge-gatekeeper:
    name: ğŸ›¡ï¸ Merge Gatekeeper
    permissions:
      checks: read
      statuses: read
    runs-on: Ubuntu-Latest
    timeout-minutes: 10

    steps:
      - name: ğŸ›¡ï¸ Run Merge Gatekeeper
        uses: upsidr/merge-gatekeeper@09af7a82c1666d0e64d2bd8c01797a0bcfd3bb5d # v1.2.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          self: ğŸ›¡ï¸ Merge Gatekeeper
          ignored: CodeRabbit

  merge-pr:
    name: ğŸ”€ Merge PR
    permissions:
      contents: write
      pull-requests: write
    needs: merge-gatekeeper
    if: ${{ github.event.pull_request.user.login == 'renovate[bot]' && github.event.sender.login == 'autofix-ci[bot]' && toJson(github.event.pull_request.requested_reviewers) == '[]' }}
    runs-on: Ubuntu-Latest
    timeout-minutes: 1

    steps:
      - name: ğŸ”€ Squash merge PR
        run: gh pr merge --repo="$GITHUB_REPOSITORY" "$GITHUB_HEAD_REF" --squash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
