name: âœ… CI Checker

on:
  pull_request:

permissions: {}

jobs:
  merge-gatekeeper:
    name: ğŸ›¡ï¸ Merge Gatekeeper
    permissions:
      checks: read
      statuses: read
    runs-on: Ubuntu-Latest
    timeout-minutes: 10

    steps:
      - name: ğŸ›¡ï¸ Run Merge Gatekeeper
        uses: upsidr/merge-gatekeeper@09af7a82c1666d0e64d2bd8c01797a0bcfd3bb5d # v1.2.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          self: ğŸ›¡ï¸ Merge Gatekeeper
          ignored: CodeRabbit

  merge-pr:
    name: ğŸ”€ Merge PR
    needs: merge-gatekeeper
    if: ${{ github.event.pull_request.user.login == 'renovate[bot]' && github.event.sender.login == 'autofix-ci[bot]' && toJson(github.event.pull_request.requested_reviewers) == '[]' }}
    runs-on: Ubuntu-Slim
    timeout-minutes: 1

    steps:
      - name: ğŸ’³ Create GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write

      - name: ğŸ”€ Squash merge PR
        run: gh pr merge --repo="$GITHUB_REPOSITORY" "$GITHUB_HEAD_REF" --squash
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

  rebase-pr:
    name: ğŸ”„ Rebase PR
    permissions:
      pull-requests: write
    needs: merge-pr
    if: ${{ failure() }}
    runs-on: Ubuntu-Slim
    timeout-minutes: 1

    steps:
      - name: ğŸšš Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: ğŸ”„ Rebase PR
        run: gh pr edit "$GITHUB_HEAD_REF" --body "$(gh pr view "$GITHUB_HEAD_REF" --json=body --jq='.body' | sed 's/- \[ \] <!-- rebase-check -->/- [x] <!-- rebase-check -->/')"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
