name: ğŸ›¡ï¸ Merge Gatekeeper

on:
  pull_request:

permissions: {}

jobs:
  merge-gatekeeper:
    permissions:
      checks: read
      statuses: read
    runs-on: Ubuntu-Latest
    timeout-minutes: 10

    steps:
      - name: ğŸ›¡ï¸ Run Merge Gatekeeper
        uses: upsidr/merge-gatekeeper@09af7a82c1666d0e64d2bd8c01797a0bcfd3bb5d # v1.2.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ignored: CodeRabbit
